# Generated by Django 4.2.14 on 2024-08-03 15:29

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import shop.orders.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('order_number', models.CharField(max_length=255)),
                ('status', enumfields.fields.EnumField(enum=shop.orders.enums.OrderStatus, max_length=10)),
                ('extra_field', models.JSONField(default=dict)),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='channels.channel')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
            ],
            options={
                'unique_together': {('order_number', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', enumfields.fields.EnumField(enum=shop.orders.enums.OrderStatus, max_length=10)),
                ('sku', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('remote_order_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_field', models.JSONField(default=dict)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
