# Generated by Django 4.2.14 on 2024-08-03 15:29

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import shop.customers.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('remote_id', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('gender', enumfields.fields.EnumField(blank=True, enum=shop.customers.enums.GenderType, max_length=10, null=True)),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='channels.channel')),
            ],
            options={
                'unique_together': {('remote_id', 'channel')},
            },
        ),
    ]
