# Generated by Django 4.2.14 on 2024-08-03 15:29

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import shop.channels.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('channel_type', enumfields.fields.EnumField(enum=shop.channels.enums.ChannelType, max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('conf', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
            },
        ),
    ]
